{
    "data": {
        "popular": {
            "platformList": [
                {
                    "vendorId": "23",
                    "vendorCode": "TB_Chess",
                    "gameCode": "800",
                    "gameNameEn": "Aviator",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                    "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                    "winOdds": 96.15,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "23",
                    "vendorCode": "TB_Chess",
                    "gameCode": "121",
                    "gameNameEn": "Chicken Road 2",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/121_20250806182119746.jpg",
                    "imgUrl2": "",
                    "winOdds": 96.60,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "23",
                    "vendorCode": "TB_Chess",
                    "gameCode": "124",
                    "gameNameEn": "Vortex",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/124_20250903165105774.png",
                    "imgUrl2": "",
                    "winOdds": 97.46,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "23",
                    "vendorCode": "TB_Chess",
                    "gameCode": "810",
                    "gameNameEn": "Cricket",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/810_20250210113250708.png",
                    "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/810_20250210102343302.png",
                    "winOdds": 97.37,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "23",
                    "vendorCode": "TB_Chess",
                    "gameCode": "100",
                    "gameNameEn": "Mines",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/100.png",
                    "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/100_20250210102610370.png",
                    "winOdds": 96.72,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "23",
                    "vendorCode": "TB_Chess",
                    "gameCode": "804",
                    "gameNameEn": "Spribe Aviator",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/804.png",
                    "imgUrl2": "",
                    "winOdds": 97.25,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                }
            ],
            "clicksTopList": [
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "51",
                    "gameNameEn": "Money Coming",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/51.png",
                    "imgUrl2": "",
                    "winOdds": 97.84,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "109",
                    "gameNameEn": "Fortune Gems",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/109.png",
                    "imgUrl2": "",
                    "winOdds": 97.80,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "49",
                    "gameNameEn": "Super Ace",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/49.png",
                    "imgUrl2": "",
                    "winOdds": 96.35,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "1",
                    "gameNameEn": "Royal Fishing",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/1.png",
                    "imgUrl2": "",
                    "winOdds": 96.93,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "27",
                    "gameNameEn": "SevenSevenSeven",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/27.png",
                    "imgUrl2": "",
                    "winOdds": 96.96,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "47",
                    "gameNameEn": "Charge Buffalo",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/47.png",
                    "imgUrl2": "",
                    "winOdds": 96.88,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "35",
                    "gameNameEn": "Crazy777",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/35.png",
                    "imgUrl2": "",
                    "winOdds": 97.44,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "17",
                    "vendorCode": "EVO_Electronic",
                    "gameCode": "grandwheel000000",
                    "gameNameEn": "Grand Wheel",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/EVO_Electronic/grandwheel000000.png",
                    "imgUrl2": "",
                    "winOdds": 96.80,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "32",
                    "gameNameEn": "JackPot Fishing",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/32.png",
                    "imgUrl2": "",
                    "winOdds": 96.94,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "82",
                    "gameNameEn": "Happy Fishing",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/82.png",
                    "imgUrl2": "",
                    "winOdds": 97.47,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "19",
                    "vendorCode": "Card365",
                    "gameCode": "707",
                    "gameNameEn": "3 Patti Classic",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/Card365/707_20250210142254071.png",
                    "imgUrl2": "",
                    "winOdds": 97.17,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "74",
                    "gameNameEn": "Mega Fishing",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/74.png",
                    "imgUrl2": "",
                    "winOdds": 96.19,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "223",
                    "gameNameEn": "Fortune Gems 2",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/223_20250213130837016.png",
                    "imgUrl2": "",
                    "winOdds": 96.46,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "45",
                    "gameNameEn": "Golden Bank",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/45.png",
                    "imgUrl2": "",
                    "winOdds": 97.17,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "17",
                    "vendorCode": "EVO_Electronic",
                    "gameCode": "777strike0000000",
                    "gameNameEn": "777 Strike",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/EVO_Electronic/777strike0000000.png",
                    "imgUrl2": "",
                    "winOdds": 96.75,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "42",
                    "gameNameEn": "Dinosaur Tycoon",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/42.png",
                    "imgUrl2": "",
                    "winOdds": 97.99,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "300",
                    "gameNameEn": "Fortune Gems 3",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/300.png",
                    "imgUrl2": "",
                    "winOdds": 97.82,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "18",
                    "vendorCode": "JILI",
                    "gameCode": "103",
                    "gameNameEn": "Golden Empire",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/103.png",
                    "imgUrl2": "",
                    "winOdds": 96.88,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                }
            ],
            "clicksVideoTopList": [
                {
                    "vendorId": "38",
                    "vendorCode": "MG_Video",
                    "gameCode": "SMG_titaniumLiveGames_Roulette",
                    "gameNameEn": "Roulette",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/MG_Video/SMG_titaniumLiveGames_Roulette.png",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "38",
                    "vendorCode": "MG_Video",
                    "gameCode": "SMG_titaniumLiveGames_Sicbo",
                    "gameNameEn": "Sicbo",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/MG_Video/SMG_titaniumLiveGames_Sicbo.png",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "10",
                    "vendorCode": "AG_Video",
                    "gameCode": "CBAC",
                    "gameNameEn": "VIP Baccarat",
                    "imgUrl": "",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "38",
                    "vendorCode": "MG_Video",
                    "gameCode": "SMG_titaniumLiveGames_Baccarat",
                    "gameNameEn": "Bonus Baccarat",
                    "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/MG_Video/SMG_titaniumLiveGames_Baccarat.png",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "10",
                    "vendorCode": "AG_Video",
                    "gameCode": "SBAC",
                    "gameNameEn": "Insurance Bacarrat",
                    "imgUrl": "",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "10",
                    "vendorCode": "AG_Video",
                    "gameCode": "NN",
                    "gameNameEn": "BullBull",
                    "imgUrl": "",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "10",
                    "vendorCode": "AG_Video",
                    "gameCode": "BJ",
                    "gameNameEn": "Blackjack",
                    "imgUrl": "",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "10",
                    "vendorCode": "AG_Video",
                    "gameCode": "ZJH",
                    "gameNameEn": "Win Three Cards",
                    "imgUrl": "",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                },
                {
                    "vendorId": "10",
                    "vendorCode": "AG_Video",
                    "gameCode": "BF",
                    "gameNameEn": "Bull Fight",
                    "imgUrl": "",
                    "imgUrl2": "",
                    "winOdds": 0.0,
                    "isMaintain": 0,
                    "isGameSaasMaintain": 0
                }
            ]
        },
        "sport": [],
        "video": [
            {
                "slotsTypeID": 16,
                "slotsName": "EVO_Video",
                "vendorId": 16,
                "vendorCode": "EVO_Video",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_20240102165020x66i.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "slotsTypeID": 10,
                "slotsName": "AG_Video",
                "vendorId": 10,
                "vendorCode": "AG_Video",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_20250607153643tj7w.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "slotsTypeID": 38,
                "slotsName": "MG_Video",
                "vendorId": 38,
                "vendorCode": "MG_Video",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_202405081133481rmp.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            }
        ],
        "slot": [
            {
                "slotsTypeID": 18,
                "slotsName": "JILI",
                "vendorId": 18,
                "vendorCode": "JILI",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_20250210101450ooy8.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "slotsTypeID": 4,
                "slotsName": "MG",
                "vendorId": 4,
                "vendorCode": "MG",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_202401021653336o2h.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "slotsTypeID": 17,
                "slotsName": "EVO_Electronic",
                "vendorId": 17,
                "vendorCode": "EVO_Electronic",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_20250210101616beik.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "slotsTypeID": 5,
                "slotsName": "PG",
                "vendorId": 5,
                "vendorCode": "PG",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_20250210101541uomm.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "slotsTypeID": 41,
                "slotsName": "G9",
                "vendorId": 41,
                "vendorCode": "G9",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_20250210101325vpri.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "slotsTypeID": 46,
                "slotsName": "BGAMING",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_20250830165429a9ho.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            }
        ],
        "chess": [
            {
                "slotsTypeID": 19,
                "slotsName": "Card365",
                "vendorId": 19,
                "vendorCode": "Card365",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_20240102164947dvuc.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "slotsTypeID": 44,
                "slotsName": "KoolBet",
                "vendorId": 44,
                "vendorCode": "KoolBet",
                "state": 1,
                "vendorImg": "https://ossimg.91admin123admin.com/91club/vendorlogo/vendorlogo_202508301653344yfb.png",
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            }
        ],
        "fish": [
            {
                "gameID": "32",
                "gameNameEn": "JackPot Fishing",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/32.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "42",
                "gameNameEn": "Dinosaur Tycoon",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/42.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "60",
                "gameNameEn": "Dragon Fortune",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/60.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "71",
                "gameNameEn": "Boom Legend",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/71.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "74",
                "gameNameEn": "Mega Fishing",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/74.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "82",
                "gameNameEn": "Happy Fishing",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/82.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "1",
                "gameNameEn": "Royal Fishing",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/1.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "119",
                "gameNameEn": "All-star Fishing",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/119.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "20",
                "gameNameEn": "Bombing Fishing",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/20.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "212",
                "gameNameEn": "Dinosaur Tycoon II",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/212.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "531",
                "gameNameEn": "Fortune Zombie",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/531_20250716173930344.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "667",
                "gameNameEn": "Circus Jackpot",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/667_20251210144614590.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            }
        ],
        "flash": [
            {
                "gameID": "800",
                "gameNameEn": "Aviator",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "121",
                "gameNameEn": "Chicken Road 2",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/121_20250806182119746.jpg",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "124",
                "gameNameEn": "Vortex",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/124_20250903165105774.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "810",
                "gameNameEn": "Cricket",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/810_20250210113250708.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/810_20250210102343302.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "100",
                "gameNameEn": "Mines",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/100.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/100_20250210102610370.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "804",
                "gameNameEn": "Spribe Aviator",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/804.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "811",
                "gameNameEn": "Mines Pro",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/811_20250210111531137.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/811_20250210102457796.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "110",
                "gameNameEn": "Limbo",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/110_20250210111637635.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/110_20250210102531478.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "812",
                "gameNameEn": "Javelin",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/812_20250314095609475.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "903",
                "gameNameEn": "DragonTiger",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/903_20250210111422071.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/903_20250210111422103.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "105",
                "gameNameEn": "Goal",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/105_20250210113618898.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/105_20250210113618945.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "120",
                "gameNameEn": "Snakes",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/120.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "102",
                "gameNameEn": "Dice",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/102_20250210111705541.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/102_20250210102559317.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "116",
                "gameNameEn": "King And Pauper",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/116.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "504",
                "gameNameEn": "Hilo Wave",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/504.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "505",
                "gameNameEn": "Clash Of Hands",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/505.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "103",
                "gameNameEn": "Plinko",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/103_20250210111953841.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/103_20250210102957755.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "500",
                "gameNameEn": "Bomb Wave",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/500_20250210111515519.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/500_20250210111515551.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "101",
                "gameNameEn": "Hilo",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/101_20250210111652965.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/101_20250210102547898.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "501",
                "gameNameEn": "Treasure Wave",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/501_20250210111454539.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/501_20250210111454570.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "107",
                "gameNameEn": "Hotline",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/107.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/107_20250210102621503.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "111",
                "gameNameEn": "Cryptos",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/111_20250210111910188.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/111_20250210102818079.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "108",
                "gameNameEn": "Space Dice",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/108_20250210111925043.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/108_20250210102832504.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "502",
                "gameNameEn": "Goal Wave",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/502_20250210111723255.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/502_20250210102634845.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "104",
                "gameNameEn": "Mini Roulette",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/104_20250210111939890.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/104_20250210102944301.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "114",
                "gameNameEn": "HorseRacing",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/114_20250210111823763.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/114_20250210102737194.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "900",
                "gameNameEn": "Keno80",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/900_20250210112011401.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/900_20250210103014351.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "106",
                "gameNameEn": "Keno",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/106.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/106_20250210102847401.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "113",
                "gameNameEn": "Pharaoh",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/113_20250210111843895.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/113_20250210102751084.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "112",
                "gameNameEn": "Triple",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/112_20250210111856804.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/112_20250210102805495.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "118",
                "gameNameEn": "DrawPoker",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/118_20250210111753896.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/118_20250210102701572.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "503",
                "gameNameEn": "Coin Wave",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/503_20250314095439321.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "119",
                "gameNameEn": "Treasure",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/119_20250210111739604.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/119_20250210102647806.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "109",
                "gameNameEn": "Coinflip",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/109_20250210112028682.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/109_20250210103027904.png",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "224",
                "gameNameEn": "Go Rush",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/224_20250213130849608.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "236",
                "gameNameEn": "Wheel",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/236.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "439",
                "gameNameEn": "Super Ace Scratch",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/439_20251022101853578.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "462",
                "gameNameEn": "Cricket Roulette",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/462_20251022102150090.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "273",
                "gameNameEn": "Keno Super Chance",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/273_20250320091127196.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "419",
                "gameNameEn": "Penalty Kicks",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/419_20250430142822112.png",
                "vendorId": 18,
                "vendorCode": "JILI",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "813",
                "gameNameEn": "Rocket",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/813.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "122",
                "gameNameEn": "Penalty",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/122_20250910151730480.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "125",
                "gameNameEn": "Aviamasters",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/125_20250929152533151.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "126",
                "gameNameEn": "Pawsome Plinko",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/126_20260102135805528.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "908",
                "gameNameEn": "7Up7Down",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/908_20260102135821282.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "814",
                "gameNameEn": "Andar Bahar",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/814_20250813154500710.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "123",
                "gameNameEn": "Chicken Road",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/123_20250820152506776.png",
                "vendorId": 23,
                "vendorCode": "TB_Chess",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "BlackjackPro",
                "gameNameEn": "Multihand Blackjack Pro",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/BlackjackPro.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "DiceClash",
                "gameNameEn": "Dice Clash",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/DiceClash.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "DragonsCrash",
                "gameNameEn": "Dragon's Crash",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/DragonsCrash.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "FishingClub",
                "gameNameEn": "Fishing Club",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/FishingClub.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "HeadsTails",
                "gameNameEn": "Heads and Tails",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/HeadsTails.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "HeadsTailsXY",
                "gameNameEn": "Heads and Tails XY",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/HeadsTailsXY.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "Minesweeper",
                "gameNameEn": "Minesweeper",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/Minesweeper.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "MinesweeperXY",
                "gameNameEn": "Minesweeper XY",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/MinesweeperXY.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "MultihandBlackjack",
                "gameNameEn": "Multihand Blackjack",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/MultihandBlackjack.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "MultihandBlackjackPro2",
                "gameNameEn": "Multihand Blackjack Pro 2",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/MultihandBlackjackPro2.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "RocketDice",
                "gameNameEn": "Rocket Dice",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/RocketDice.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "RocketDiceXY",
                "gameNameEn": "Rocket Dice XY",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/RocketDiceXY.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "SpaceXY",
                "gameNameEn": "Space XY",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/SpaceXY.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "gameID": "WinterFishingClub",
                "gameNameEn": "Winter Fishing Club",
                "img": "https://ossimg.91admin123admin.com/91club/gamelogo/BGAMING/WinterFishingClub.png",
                "vendorId": 46,
                "vendorCode": "BGAMING",
                "imgUrl2": "",
                "customGameType": 0,
                "typeId": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            }
        ],
         "lottery": [
            {
                "id": 1,
                "categoryCode": "Win Go",
                "categoryName": "WinGo彩票",
                "state": 1,
                "sort": 10,
                "categoryImg": "https://ossimg.91admin123admin.com/91club/lotterycategory/lotterycategory_202502101011154e3a.png",
                "wingoAmount": null,
                "k3Amount": null,
                "fiveDAmount": null,
                "trxWingoAmount": null
            },
            {
                "id": 2,
                "categoryCode": "K3",
                "categoryName": "K3彩票",
                "state": 1,
                "sort": 8,
                "categoryImg": "https://ossimg.91admin123admin.com/91club/lotterycategory/lotterycategory_20250210101053ntrf.png",
                "wingoAmount": null,
                "k3Amount": null,
                "fiveDAmount": null,
                "trxWingoAmount": null
            },
            {
                "id": 3,
                "categoryCode": "5D",
                "categoryName": "5D彩票",
                "state": 1,
                "sort": 1,
                "categoryImg": "https://ossimg.91admin123admin.com/91club/lotterycategory/lotterycategory_20250210101042iwui.png",
                "wingoAmount": null,
                "k3Amount": null,
                "fiveDAmount": null,
                "trxWingoAmount": null
            },
            {
                "id": 4,
                "categoryCode": "Trx Win Go",
                "categoryName": "TrxWinGo彩票",
                "state": 1,
                "sort": 0,
                "categoryImg": "https://ossimg.91admin123admin.com/91club/lotterycategory/lotterycategory_20250210101104jtse.png",
                "wingoAmount": null,
                "k3Amount": null,
                "fiveDAmount": null,
                "trxWingoAmount": null
            },
            {
                "id": 0,
                "categoryCode": "Win Go",
                "categoryName": "WinGo彩票",
                "state": 1,
                "sort": 0,
                "categoryImg": "https://ossimg.55club-55club.com/55club/lotterycategory/lotterycategory_20250425042914ibbt.png",
                "wingoAmount": null,
                "k3Amount": null,
                "fiveDAmount": null,
                "trxWingoAmount": null
            }
        ],
        "awardRecordList": [
            {
                "orderId": 19889479,
                "userId": 661270,
                "userPhoto": "5",
                "userName": "919812196905",
                "gameName": "Monkey Party",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/67.png",
                "imgUrl2": "",
                "multiple": 15.00,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889478,
                "userId": 18955745,
                "userPhoto": "15",
                "userName": "916287356814",
                "gameName": "Aviator",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "multiple": 11.65,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889477,
                "userId": 15132107,
                "userPhoto": "19",
                "userName": "918475835920",
                "gameName": "Aviator",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "multiple": 11.65,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889476,
                "userId": 12605608,
                "userPhoto": "1",
                "userName": "917857926210",
                "gameName": "Aviator",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "multiple": 11.26,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889475,
                "userId": 4983734,
                "userPhoto": "2",
                "userName": "919155976914",
                "gameName": "Aviator",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "multiple": 10.96,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889474,
                "userId": 13362960,
                "userPhoto": "1",
                "userName": "919235266183",
                "gameName": "Aviator",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "multiple": 10.83,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889473,
                "userId": 19408778,
                "userPhoto": "1",
                "userName": "918757571917",
                "gameName": "Aviator",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "multiple": 10.70,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889472,
                "userId": 12027651,
                "userPhoto": "15",
                "userName": "919606705732",
                "gameName": "Aviator",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "multiple": 10.50,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889471,
                "userId": 9744392,
                "userPhoto": "1",
                "userName": "918221914087",
                "gameName": "Aviator",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151122.png",
                "imgUrl2": "https://ossimg.91admin123admin.com/91club/gamelogo/TB_Chess/800_20250210113151154.png",
                "multiple": 10.46,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            },
            {
                "orderId": 19889470,
                "userId": 661270,
                "userPhoto": "5",
                "userName": "919812196905",
                "gameName": "Monkey Party",
                "imgUrl": "https://ossimg.91admin123admin.com/91club/gamelogo/JILI/67.png",
                "imgUrl2": "",
                "multiple": 10.00,
                "bonusAmount": 35.00,
                "multipleName": "10-19.9",
                "createTime": "2026-02-14 13:54:01",
                "targetVendorCode": "",
                "targetGameCode": ""
            }
        ]
    },
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "serviceNowTime": "2026-02-14 14:27:00"
}