{
    "data": [
        {
            "title": "⚠️ Withdrawal Security Alert ⚠️",
            "siteMessage": "<p style=\"text-align: center; \"><img src=\"https://ossimg.91admin123admin.com/91club/editor/editor_202510290359541ex1.png\" style=\"width: 100%;\"><br></p>",
            "sort": 999999999,
            "addtime": "2025-10-29 04:00:41"
        },
        {
            "title": "📢  IMPORTANT NOTICE",
            "siteMessage": "<p style=\"text-align: center;\"><img src=\"https://ossimg.91admin123admin.com/91club/editor/editor_20250826125903a2i6.png\" style=\"font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; width: 205px;\"></p><p style=\"text-align: center; \"><b><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\">[ .in ] Domain Expiry<br></font></font></font></font></font></font></b><b style=\"\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><br><font face=\"Helvetica Neue, Helvetica, Arial, sans-serif\">Our [ .in ] domains will expire soon.<br></font></font></font></font></font></font></font></b><span style=\"font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><b>Please use our </b><a href=\"http://99club.vbrao.com/\" target=\"_blank\" style=\"\"><b>MAIN DOMAIN</b></a><b> or contact Customer Service / your Upline for the latest active domain to avoid service interruption.</b><br></font></font></font></font></font></font></span><span style=\"font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><font dir=\"auto\" style=\"vertical-align: inherit;\"><br><a href=\"https://99club.vbrao.com/\" target=\"_blank\" style=\"\"><b>MAIN DOMAIN CLICK HERE</b></a></font></font></font></font></font></font></span></p>",
            "sort": 10000000,
            "addtime": "2025-08-26 13:09:36"
        },
        {
            "title": "🎁  GIFT CODE  🎁",
            "siteMessage": "<p style=\"text-align: center; \"></p><div style=\"text-align: center;\"><font face=\"Comic Sans MS\"><b><span style=\"font-family: Arial;\">❤️ Your JOY is our PRIORITY ❤️</span></b></font></div><div style=\"text-align: center;\"><font face=\"Microsoft YaHei\"><b><br></b></font></div><span style=\"font-family: Arial;\"><div style=\"text-align: center;\"><b>Download 99club APP now</b></div></span><div style=\"text-align: left; background-color: rgb(255, 255, 255);\"><div style=\"text-align: center;\"><span style=\"text-align: left; font-family: Arial;\"><font color=\"#337ab7\" face=\"Comic Sans MS\"><b>➡️</b></font></span><a href=\"https://99club.vbrao.com.apk\" target=\"_blank\" style=\"font-family: &quot;Microsoft YaHei&quot;; background-color: rgb(255, 255, 255);\"><span style=\"font-family: Arial;\"><b>CLICK HERE TO DOWNLOAD</b></span></a><span style=\"font-family: Arial;\"></span><span style=\"text-align: left; font-family: Arial;\"><font color=\"#337ab7\" face=\"Comic Sans MS\"><b>⬅️</b></font></span></div><div style=\"text-align: center;\"><font face=\"Microsoft YaHei\"><b><br></b></font></div><b><font face=\"Microsoft YaHei\"><div style=\"text-align: center;\"></div></font><a href=\"https://91appl.com/download/ar048/full.apk\" target=\"_blank\" style=\"font-family: &quot;Microsoft YaHei&quot;; background-color: rgb(255, 255, 255);\"></a></b></div><div style=\"text-align: center;\"><img src=\"https://ossimg.91admin123admin.com/91club/editor/editor_20250902152422igc4.png\" style=\"width: 125px;\"><font face=\"Microsoft YaHei\"><b><br></b></font></div><div style=\"text-align: left;\"><div style=\"text-align: center;\"><font face=\"Comic Sans MS\"><b><span style=\"font-family: Arial;\">⚠️ Don’t miss it !</span></b></font></div><div style=\"text-align: center;\"><font face=\"Comic Sans MS\"><b><span style=\"font-family: Arial;\">Daily gift codes waiting for you in the app !</span></b></font></div><div style=\"text-align: center;\"><font face=\"Comic Sans MS\"><b><br></b></font></div><div style=\"text-align: center; \"><font face=\"Comic Sans MS\"><b><span style=\"font-family: Arial;\">🎁 Check the </span><a href=\"/#/activity\" target=\"_blank\">Activity Page</a><span style=\"font-family: Arial;\"> for more bonuses! 🎁</span></b></font></div></div><p></p>",
            "sort": 10000,
            "addtime": "2025-09-02 15:24:25"
        }
    ],
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "serviceNowTime": "2026-03-12 19:14:02"
}